### ISSUE TITLE
Implement a logic to execute and render js expressions in CWL Schema

### ISSUE THREAD

**Issue by nsyzrantsev** [zefiroproj/zefiro#5]
## Description

Implement a logic to [zefiro-cwl-parser](https://github.com/zefiroproj/zefiro/tree/main/zefiro-core/zefiro-cwl-parser) crate to evaluate JavaScript expressions and populates schema fields containing expressions in the formats `$(...)`, `${...}`, or `| ${...}`. For this purpose, the [deno_core](https://github.com/denoland/deno_core) crate will be utilized.

https://www.commonwl.org/v1.2/CommandLineTool.html#Expressions_(Optional)

### Inputs:

* `fastq`: `s3://bucket/sample/file.fastq.gz` (size: 1024 MB or `1024*1024*1024` bytes)
* `fastq2`: `s3://bucket/sample/file.fastq.gz` (size: 512 MB or `512*1024*1024` bytes)

```yaml
...
inputs:
  - id: fastq
    type: File
    inputBinding:
      prefix: --fastq
  - id: fastq2
    type: File
    inputBinding:
      prefix: --fastq2
...
requirements:
  - class: ResourceRequirement
    coresMin: 8
    outdirMin: |
      ${
        var in_files_size = (inputs.fastq.size + inputs.fastq2.size) / (1024 * 1024);
        return 2 * in_files_size;
      }
  - class: ToolTimeLimit
    timelimit: $(60 * 60 * 8)
  ...
```

### Outputs:

```yaml
...
inputs:
  - id: fastq
    type: File
    inputBinding:
      prefix: --fastq
  - id: fastq2
    type: File
    inputBinding:
      prefix: --fastq2
  ...
requirements:
  - class: ResourceRequirement
    coresMin: 8
    outdirMin: 3072
  - class: ToolTimeLimit
    timelimit: 28800
  ...
```

### Questions:

1. How can expressions in the formats `$(...)`, `${...}`, or `| ${...}` be accurately matched in a schema? Should the matching rely on input paths within values and the presence of `${` or `$(` symbols at the start?
2. How should input file sizes be evaluated correctly? How it will work for remote files from AWS, GCP, Azure?
3. Which cloud platforms will be supported in the implementation? Or will the current realization work exclusively with local files?
4. What js data structure of inputs will be used? And when `basename`, `nameroot`, `nameext` etc. should be generated?
```JSON5
"inputs": {
  "fastq": {
      "class": "File",
      "location": "/path/to/input.txt",
      "basename": "input.txt",
      "nameroot": "input",
      "nameext": ".txt",
      "checksum": "0912349fasf2143",
      "size": 536870912,
  }
}
```
