### ISSUE TITLE
Develop values template render

### ISSUE THREAD

**Issue by nsyzrantsev** [zefiroproj/zefiro#8]
## Description  

Develop values template render using the [Tera](https://github.com/Keats/tera) template engine, inspired by Jinja2/Django templating engines.  

This render will be included in the [zefiro-cwl](https://github.com/zefiroproj/zefiro-cwl) repository.  

### Input Example:  
Template before rendering (`values.yml`):  
```yaml  
in_file:  
  class: File  
  location: '{{ inputLocation }}/output/input.txt'  
out_file: 'output.txt'  
```  

### Output Example:  
Rendered template with input data `{"inputLocation": "s3://bucket/sample/"}`:  
```yaml  
in_file:  
  class: File  
  location: 's3://bucket/sample/output/input.txt'  
out_file: 'output.txt'  
```

### Notes:

* `inputLocation` is a constant Jinja variable that can be replaced dynamically during the rendering process. Other variables can have a custom name.
